version: "2"
services:
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
    web:
        container_name: web
        build: ./frontend
        ports:
            - "3000:3000"
        links:
            - app
        volumes:
            - ./frontend:/app/
            - /app/node_modules
        command: npm start
    app:
        container_name: app
        restart: always
        build: ./backend
        ports:
            - "8080:8080"
        links:
            - mongo
        volumes:
            - ./backend:/app/
            - /app/node_modules
        depends_on:
            - mongo